# Generated by Django 4.2.16 on 2026-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='remaining_reviews',
            field=models.IntegerField(default=4),
        ),
    ]
